### ISSUE TITLE
Huge Error (Crashes) With Corail Recyler. (1.18.2)

### ISSUE THREAD

**Issue by Pineappleguy03** [ochotonida/some-assembly-required#29]
Seems to be an issue with a recipe

Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41619_()" because "recipeItem" is null
	at org.cursegame.minecraft.dt.recipe.RecipeProvider.loadRegisteredRecipes(RecipeProvider.java:93) ~[Corail-DT-1.18.2-465.jar%2362!/:465] {re:classloading}
	at org.cursegame.minecraft.dt.recipe.RecipeProvider.loadRegisteredRecipes(RecipeProvider.java:151) ~[Corail-DT-1.18.2-465.jar%2362!/:465] {re:classloading}
	at org.cursegame.minecraft.dt.recipe.RecipeService.loadRecipes(RecipeService.java:97) ~[Corail-DT-1.18.2-465.jar%2362!/:465] {re:classloading}
	at org.cursegame.minecraft.dt.recipe.RecipeService.initialize(RecipeService.java:73) ~[Corail-DT-1.18.2-465.jar%2362!/:465] {re:classloading}
	at org.cursegame.minecraft.dt.ModDT.onServerStarted(ModDT.java:67) ~[Corail-DT-1.18.2-465.jar%2362!/:465] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_288_ModDT_onServerStarted_ServerStartedEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:103) ~[forge-1.18.2-40.1.52-universal.jar%23145!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:662) ~[server-1.18.2-20220404.173914-srg.jar%23140!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23140!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

And yes. It's only when SAR is installed.

**Comment by ochotonida** [comment]
Should be fixed in version 2.0.8
